[package]
name = "power"
version = "0.1.0"
edition = "2024"
default-run = "power"

[lib]
doctest = false

[dependencies]
axum = { version = "0.8", features = ["macros"] }
chrono = { version = "0.4.44", features = ["serde"] }
clap = { version = "4.6.1", features = ["derive"] }
eyre = "0.6.12"
hex = "0.4.3"
log = "0.4.29"
md-5 = "0.11.0"
phf = { version = "0.13.1", features = ["macros"] }
reqwest = { version = "0.13.3", features = ["form", "json", "query"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8", features = ["runtime-tokio", "migrate", "postgres", "sqlite-unbundled"] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["fs", "trace"] }
tracing-subscriber = "0.3.23"

